#include <stdio.h>
#include <cuda_runtime.h>
#include <cusolverDn.h>
#include "matrix_ops.h"
#include "givens.h"

int verbose = 0;
int check = 0;

// Source - https://stackoverflow.com/a/14038590
// Posted by talonmies, modified by community. See post 'Timeline' for change history
// Retrieved 2026-04-14, License - CC BY-SA 4.0
#define gpuErrCheck(ans) { gpuAssert((ans), __FILE__, __LINE__); }
inline void gpuAssert(cudaError_t code, const char *file, int line, bool abort=true)
{
   if (code != cudaSuccess) 
   {
      fprintf(stderr,"GPUassert: %s %s %d\n", cudaGetErrorString(code), file, line);
      if (abort) exit(code);
   }
}

#define gpuCuSolverCheck(call) do {                       \
    cusolverStatus_t status = call;                   \
    if (status != CUSOLVER_STATUS_SUCCESS) {          \
        printf("cuSOLVER error\n");                   \
        exit(1);                                      \
    }                                                 \
} while(0)



// Source - Generated by ChatGPT (2026-04-25)
float* solve_least_squares_cuSOLVER(float *A, float *b, int M, int N) {
    float *d_A, *d_b, *d_x, *d_work;
    float *h_x;
    int lda = M, ldb = M, ldx = N;
    int *d_info, h_info;
    int niter;
    size_t lwork;

    cusolverDnHandle_t handle;
    gpuCuSolverCheck(cusolverDnCreate(&handle));

    gpuErrCheck(cudaMalloc(&d_A, M * N * sizeof(float)));
    gpuErrCheck(cudaMalloc(&d_b, M * sizeof(float)));
    gpuErrCheck(cudaMalloc(&d_x, N * sizeof(float)));
    gpuErrCheck(cudaMalloc(&d_info, sizeof(int)));

    gpuErrCheck(cudaMemcpy(d_A, A, M * N * sizeof(float), cudaMemcpyHostToDevice));
    gpuErrCheck(cudaMemcpy(d_b, b, M * sizeof(float), cudaMemcpyHostToDevice));

    // workspace query
    gpuCuSolverCheck(cusolverDnSSgels_bufferSize(
        handle, M, N, 1,
        d_A, lda,
        d_b, ldb,
        d_x, ldx,
        NULL, &lwork
    ));

    gpuErrCheck(cudaMalloc(&d_work, lwork * sizeof(float)));

    // solve
    gpuCuSolverCheck(cusolverDnSSgels(
        handle, M, N, 1,
        d_A, lda,
        d_b, ldb,
        d_x, ldx,
        d_work, lwork,
        &niter,
        d_info
    ));

    gpuErrCheck(cudaMemcpy(&h_info, d_info, sizeof(int), cudaMemcpyDeviceToHost));
    if (h_info != 0) {
        printf("Solver failed: %d\n", h_info);
    }

    h_x = (float*)malloc(N * sizeof(float));
    gpuErrCheck(cudaMemcpy(h_x, d_x, N * sizeof(float), cudaMemcpyDeviceToHost));

    cudaFree(d_A);
    cudaFree(d_b);
    cudaFree(d_x);
    cudaFree(d_work);
    cudaFree(d_info);
    cusolverDnDestroy(handle);

    return h_x;
}


float* solve_least_squares_Givens(float *A, float *b, int M, int N) {

    float* Rb = (float*) malloc (sizeof(float) * M * (N + 1));
    for (size_t i = 0; i < M; i++)
    for (size_t j = 0; j < N; j++)
        Rb[i*(N + 1) + j] = A[i*N + j];
    for (size_t i = 0; i < M; i++)
        Rb[i*(N + 1) + N] = b[i];
    
    if (verbose) print_matrix(Rb, M, N + 1);
    if (verbose) printf("-------------------\n");


    int threads = 256;
    int blocks = (M*(N + 1) + 255) / 256;
    size_t* leftmost;
    size_t* downmost;
    cudaMallocManaged(&leftmost, sizeof(size_t)*M);
    cudaMallocManaged(&downmost, sizeof(size_t)*N);
    for (int i = 0; i < M; i++) leftmost[i] = 0;
    for (int i = 0; i < N; i++) downmost[i] = M - 1;

    float* Rb1_d;
    float* Rb2_d;
    gpuErrCheck( cudaMalloc(&Rb1_d, M*(N + 1)*sizeof(float)) );
    gpuErrCheck( cudaMalloc(&Rb2_d, M*(N + 1)*sizeof(float)) );
    gpuErrCheck( cudaMemcpy(Rb1_d, Rb, M*(N + 1)*sizeof(float), cudaMemcpyHostToDevice) );

    printf("Malloc and memcpy done, calling Kernel...\n");

    int iter = 0;
    int swap = 0;
    while (1) {
        givens_gpu_LLS<<<blocks, threads>>>(
            Rb1_d, Rb2_d,
            M, N, leftmost, downmost, swap
        );
        gpuErrCheck( cudaPeekAtLastError() );
        gpuErrCheck( cudaDeviceSynchronize() );

        printf("Iteration %d done.\n", ++iter);

        size_t i = N - 1;
        for (;;) {
          size_t start = i ? downmost[i - 1] + 1 : 0;
          size_t end = downmost[i];
          for (size_t j = 1 + (start + end) / 2; j <= end; j++) leftmost[j]++;
          
          downmost[i] -= (1 + end - start) / 2;
          if (i == 0) break;
          else i--;
        }
        
        if (verbose) {
          for (int i = 0; i < N; i++) printf("%zu ", downmost[i]);
          printf("\n");
          for (int i = 0; i < M; i++) printf("%zu ", leftmost[i]);
          printf("\n");
        }

        size_t mn = min(M, N);
        if (downmost[mn - 1] == mn - 1) break;
        swap = swap ^ 1;

    }

    gpuErrCheck( cudaMemcpy(Rb, swap ? Rb1_d : Rb2_d, M*(N + 1)*sizeof(float), cudaMemcpyDeviceToHost) );

    if (verbose) print_matrix(Rb, M, N + 1);
    if (verbose) printf("-------------------\n");

    printf("Givens done after %d iterations.\nSwap is %d\n", iter, swap);

    float* ans = (float*) malloc (sizeof(float) * N);
    for (int i = N - 1; i >= 0; i--) {
        float rhs = Rb[i*(N + 1) + N];
        for (int j = N - 1; j > i; j--) {
            rhs -= ans[j] * Rb[i*(N + 1) + j];
        }
        ans[i] = rhs / Rb[i*(N + 1) + i];
    }

    return ans;
}


float compute_residual(float *A, float *x, float *b, int M, int N) {
    float *Ax = (float*)malloc(M * sizeof(float));
    matmul_f(A, x, Ax, M, N, 1);
    float err = 0.0f;
    for (int i = 0; i < M; i++) {
        float r = Ax[i] - b[i];
        err += r * r;
    }
    free(Ax);
    return err;
}



int main(int argc, char* argv[]) {

    if (argc > 2) check = 1;
    if (argc > 3) verbose = 1;

    float *A, *b;
    size_t M = 1000, N = 50;       // dimensions of A
    generate_random(&A, M, N);
    generate_random(&b, M, 1);

    float* v_householder = solve_least_squares_cuSOLVER(A, b, M, N);
    float* v_givens = solve_least_squares_Givens(A, b, M, N);    

    float err_householder = compute_residual(A, v_householder, b, M, N);
    float err_givens = compute_residual(A, v_givens, b, M, N);

    printf("~ Resulting residual errors ~\nHouseholder: %.10f | Givens: %.10f\n", err_householder, err_givens);
}