#include <stdio.h>
#include <cuda_runtime.h>
#include <cusolverDn.h>
#include "matrix_ops.h"
#include "givens.h"

int verbose = 0;
int check = 0;

// Source - https://stackoverflow.com/a/14038590
// Posted by talonmies, modified by community. See post 'Timeline' for change history
// Retrieved 2026-04-14, License - CC BY-SA 4.0
#define gpuErrCheck(ans) { gpuAssert((ans), __FILE__, __LINE__); }
inline void gpuAssert(cudaError_t code, const char *file, int line, bool abort=true)
{
   if (code != cudaSuccess) 
   {
      fprintf(stderr,"GPUassert: %s %s %d\n", cudaGetErrorString(code), file, line);
      if (abort) exit(code);
   }
}

#define gpuCuSolverCheck(call) do {                       \
    cusolverStatus_t status = call;                   \
    if (status != CUSOLVER_STATUS_SUCCESS) {          \
        printf("cuSOLVER error\n");                   \
        exit(1);                                      \
    }                                                 \
} while(0)



// Source - Generated by Claude AI (2026-04-27)
float* solve_least_squares_cuSOLVER(float *A, float *b, int M, int N) {
    float *d_A, *d_b, *d_tau, *d_work;
    float *h_b, *h_A, *h_x;
    int *d_info;
    int h_info;
    int lwork_geqrf = 0, lwork_ormqr = 0, lwork = 0;

    cusolverDnHandle_t handle;
    gpuCuSolverCheck(cusolverDnCreate(&handle));

    gpuErrCheck(cudaMalloc(&d_A,   M * N * sizeof(float)));
    gpuErrCheck(cudaMalloc(&d_b,   M * sizeof(float)));
    gpuErrCheck(cudaMalloc(&d_tau, N * sizeof(float)));
    gpuErrCheck(cudaMalloc(&d_info, sizeof(int)));

    gpuErrCheck(cudaMemcpy(d_A, A, M * N * sizeof(float), cudaMemcpyHostToDevice));
    gpuErrCheck(cudaMemcpy(d_b, b, M * sizeof(float),     cudaMemcpyHostToDevice));

    // ----------------------------------------------------------------
    // Step 1: Workspace query then QR factorization  A = Q * R
    //         On exit, d_A holds the packed Householder reflectors
    //         (below diagonal) and R (upper triangle). d_tau holds
    //         the scalar factors of each elementary reflector.
    // ----------------------------------------------------------------
    gpuCuSolverCheck(cusolverDnSgeqrf_bufferSize(handle, M, N, d_A, M, &lwork_geqrf));
    gpuCuSolverCheck(cusolverDnSormqr_bufferSize(
        handle,
        CUBLAS_SIDE_LEFT, CUBLAS_OP_T,
        M, 1, N,
        d_A, M,
        d_tau,
        d_b, M,
        &lwork_ormqr
    ));

    lwork = (lwork_geqrf > lwork_ormqr) ? lwork_geqrf : lwork_ormqr;
    gpuErrCheck(cudaMalloc(&d_work, lwork * sizeof(float)));

    gpuCuSolverCheck(cusolverDnSgeqrf(handle, M, N, d_A, M, d_tau, d_work, lwork, d_info));

    gpuErrCheck(cudaMemcpy(&h_info, d_info, sizeof(int), cudaMemcpyDeviceToHost));
    if (h_info != 0) {
        fprintf(stderr, "sgeqrf failed: %d\n", h_info);
        return NULL;
    }

    // ----------------------------------------------------------------
    // Step 2: Apply Q^T to b in-place:  b <- Q^T * b
    //         After this, the first N entries of d_b are Q^T*b
    //         restricted to the column space; entries [N..M-1] are
    //         the residual components.
    // ----------------------------------------------------------------
    gpuCuSolverCheck(cusolverDnSormqr(
        handle,
        CUBLAS_SIDE_LEFT, CUBLAS_OP_T,
        M, 1, N,
        d_A, M,
        d_tau,
        d_b, M,
        d_work, lwork,
        d_info
    ));

    gpuErrCheck(cudaMemcpy(&h_info, d_info, sizeof(int), cudaMemcpyDeviceToHost));
    if (h_info != 0) {
        fprintf(stderr, "sormqr failed: %d\n", h_info);
        return NULL;
    }

    // ----------------------------------------------------------------
    // Step 3: Copy R and Q^T*b back to host for back substitution.
    //         R is the N×N upper triangle of the M×N packed matrix.
    // ----------------------------------------------------------------
    h_A = (float*)malloc(M * N * sizeof(float));
    h_b = (float*)malloc(M * sizeof(float));
    h_x = (float*)malloc(N * sizeof(float));

    gpuErrCheck(cudaMemcpy(h_A, d_A, M * N * sizeof(float), cudaMemcpyDeviceToHost));
    gpuErrCheck(cudaMemcpy(h_b, d_b, M * sizeof(float),     cudaMemcpyDeviceToHost));

    // ----------------------------------------------------------------
    // Step 4: Manual back substitution  R * x = (Q^T b)[0:N]
    //         R is upper triangular, stored column-major with lda=M.
    // ----------------------------------------------------------------
    for (int i = N - 1; i >= 0; i--) {
        float sum = h_b[i];
        for (int j = i + 1; j < N; j++) {
            sum -= h_A[j * M + i] * h_x[j];  // column-major: R[i,j] = h_A[j*M + i]
        }
        h_x[i] = sum / h_A[i * M + i];        // R[i,i] = h_A[i*M + i]
    }

    free(h_A);
    free(h_b);

    cudaFree(d_A);
    cudaFree(d_b);
    cudaFree(d_tau);
    cudaFree(d_work);
    cudaFree(d_info);
    cusolverDnDestroy(handle);

    return h_x;
    // float *d_A, *d_b, *d_x, *d_work;
    // float *h_x;
    // int lda = M, ldb = M, ldx = N;
    // int *d_info, h_info;
    // int niter;
    // size_t lwork;

    // cusolverDnHandle_t handle;
    // gpuCuSolverCheck(cusolverDnCreate(&handle));

    // gpuErrCheck(cudaMalloc(&d_A, M * N * sizeof(float)));
    // gpuErrCheck(cudaMalloc(&d_b, M * sizeof(float)));
    // gpuErrCheck(cudaMalloc(&d_x, N * sizeof(float)));
    // gpuErrCheck(cudaMalloc(&d_info, sizeof(int)));

    // gpuErrCheck(cudaMemcpy(d_A, A, M * N * sizeof(float), cudaMemcpyHostToDevice));
    // gpuErrCheck(cudaMemcpy(d_b, b, M * sizeof(float), cudaMemcpyHostToDevice));

    // // workspace query
    // gpuCuSolverCheck(cusolverDnSSgels_bufferSize(
    //     handle, M, N, 1,
    //     d_A, lda,
    //     d_b, ldb,
    //     d_x, ldx,
    //     NULL, &lwork
    // ));

    // gpuErrCheck(cudaMalloc(&d_work, lwork * sizeof(float)));

    // // solve
    // gpuCuSolverCheck(cusolverDnSSgels(
    //     handle, M, N, 1,
    //     d_A, lda,
    //     d_b, ldb,
    //     d_x, ldx,
    //     d_work, lwork,
    //     &niter,
    //     d_info
    // ));

    // gpuErrCheck(cudaMemcpy(&h_info, d_info, sizeof(int), cudaMemcpyDeviceToHost));
    // if (h_info != 0) {
    //     printf("Solver failed: %d\n", h_info);
    // }

    // h_x = (float*)malloc(N * sizeof(float));
    // gpuErrCheck(cudaMemcpy(h_x, d_x, N * sizeof(float), cudaMemcpyDeviceToHost));

    // cudaFree(d_A);
    // cudaFree(d_b);
    // cudaFree(d_x);
    // cudaFree(d_work);
    // cudaFree(d_info);
    // cusolverDnDestroy(handle);

    // return h_x;
}


float* solve_least_squares_Givens(float *A, float *b, int M, int N) {

    float* Rb = (float*) malloc (sizeof(float) * M * (N + 1));
    for (size_t i = 0; i < M; i++)
    for (size_t j = 0; j < N; j++)
        Rb[i*(N + 1) + j] = A[i*N + j];
    for (size_t i = 0; i < M; i++)
        Rb[i*(N + 1) + N] = b[i];
    
    if (verbose) print_matrix(Rb, M, N + 1);
    if (verbose) printf("-------------------\n");


    int threads = 256;
    int blocks = (M*(N + 1) + 255) / 256;
    size_t* leftmost = (size_t*) malloc (sizeof(size_t) * M);
    size_t* leftmost_d;
    size_t* downmost;

    gpuErrCheck( cudaMalloc(&leftmost_d, sizeof(size_t)*M) );
    gpuErrCheck( cudaMallocManaged(&downmost, sizeof(size_t)*N) );
    for (int i = 0; i < M; i++) leftmost[i] = 0;
    for (int i = 0; i < N; i++) downmost[i] = M - 1;
    gpuErrCheck( cudaMemcpy(leftmost_d, leftmost, M*sizeof(size_t), cudaMemcpyHostToDevice) );
    free(leftmost);

    float* Rb1_d;
    float* Rb2_d;
    gpuErrCheck( cudaMalloc(&Rb1_d, M*(N + 1)*sizeof(float)) );
    gpuErrCheck( cudaMalloc(&Rb2_d, M*(N + 1)*sizeof(float)) );
    gpuErrCheck( cudaMemcpy(Rb1_d, Rb, M*(N + 1)*sizeof(float), cudaMemcpyHostToDevice) );

    printf("Malloc and memcpy done, calling Kernel...\n");

    int iter = 0;
    int swap = 0;
    size_t mn = min(M, N);
    if (M == N) mn--;

    while (1) {
        givens_gpu_LLS<<<blocks, threads>>>(
            Rb1_d, Rb2_d,
            M, N, leftmost_d, downmost, swap
        );
        gpuErrCheck( cudaPeekAtLastError() );
        gpuErrCheck( cudaDeviceSynchronize() );

        printf("Iteration %d done.\n", ++iter);

        int blocksUpdLeft = (M + threads - 1) / threads;
        update_leftmost<<<blocksUpdLeft, threads>>>(
            leftmost_d, downmost, M, N
        );
        gpuErrCheck( cudaPeekAtLastError() );
        gpuErrCheck( cudaDeviceSynchronize() );

        update_downmost<<<1, N>>>(downmost);
        gpuErrCheck( cudaPeekAtLastError() );
        gpuErrCheck( cudaDeviceSynchronize() );

        
        // if (verbose) {
        //   for (int i = 0; i < N; i++) printf("%zu ", downmost[i]);
        //   printf("\n");
        //   for (int i = 0; i < M; i++) printf("%zu ", leftmost[i]);
        //   printf("\n");
        // }

        if (downmost[mn - 1] == mn - 1) break;
        swap = swap ^ 1;
    }

    gpuErrCheck( cudaMemcpy(Rb, swap ? Rb1_d : Rb2_d, M*(N + 1)*sizeof(float), cudaMemcpyDeviceToHost) );

    if (verbose) print_matrix(Rb, M, N + 1);
    if (verbose) printf("-------------------\n");

    printf("Givens done after %d iterations.\nSwap is %d\n", iter, swap);

    float* ans = (float*) malloc (sizeof(float) * N);
    for (int i = N - 1; i >= 0; i--) {
        float rhs = Rb[i*(N + 1) + N];
        for (int j = N - 1; j > i; j--) {
            rhs -= ans[j] * Rb[i*(N + 1) + j];
        }
        ans[i] = rhs / Rb[i*(N + 1) + i];
    }

    return ans;
}


float compute_residual(float *A, float *x, float *b, int M, int N) {
    float *Ax = (float*)malloc(M * sizeof(float));
    matmul_f(A, x, Ax, M, N, 1);
    float err = 0.0f;
    for (int i = 0; i < M; i++) {
        float r = Ax[i] - b[i];
        err += r * r;
    }
    free(Ax);
    return err;
}



int main(int argc, char* argv[]) {

    mt_seed((uint32_t)time(NULL));

    if (argc > 2) check = 1;
    if (argc > 3) verbose = 1;

    float *A, *b;
    size_t M = 10, N = 10;       // dimensions of A
    generate_random(&A, M, N);
    generate_random(&b, M, 1);

    float* v_householder = solve_least_squares_cuSOLVER(A, b, M, N);
    float* v_givens = solve_least_squares_Givens(A, b, M, N);    

    float err_householder = compute_residual(A, v_householder, b, M, N);
    float err_givens = compute_residual(A, v_givens, b, M, N);

    printf("~ Resulting residual errors ~\nHouseholder: %.10f | Givens: %.10f\n", err_householder, err_givens);
}